"""Aumento lunghezza descrizione

Revision ID: 31bda445c977
Revises: b5cec667f60c
Create Date: 2025-03-19 11:35:59.418489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31bda445c977'
down_revision = 'b5cec667f60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ricetta', schema=None) as batch_op:
        batch_op.alter_column('descrizione',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ricetta', schema=None) as batch_op:
        batch_op.alter_column('descrizione',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
