"""modifica campo total_time con db.string

Revision ID: 7f9ca36328cf
Revises: 333cca0a1736
Create Date: 2025-05-09 10:46:11.952054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f9ca36328cf'
down_revision = '333cca0a1736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ricetta', schema=None) as batch_op:
        batch_op.alter_column('total_time',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ricetta', schema=None) as batch_op:
        batch_op.alter_column('total_time',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
