"""aggiunta della tabella accessLog

Revision ID: 8f9365dae15e
Revises: 31bda445c977
Create Date: 2025-04-08 18:22:00.028397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9365dae15e'
down_revision = '31bda445c977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prima_visita', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ultima_visita', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ultima_visita')
        batch_op.drop_column('prima_visita')

    # ### end Alembic commands ###
