"""modifica del campo immagine in string(255)

Revision ID: f9b434b18ad9
Revises: 7f9ca36328cf
Create Date: 2025-05-13 18:08:35.416353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9b434b18ad9'
down_revision = '7f9ca36328cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ricetta', schema=None) as batch_op:
        batch_op.alter_column('immagine',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ricetta', schema=None) as batch_op:
        batch_op.alter_column('immagine',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
